import { ReportUser } from "@/stores/analytics.store";

export const MOCK_REPORTS: ReportUser[] = [
  {
    id: "rep-001",
    name: "Alex Rivera",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    course: "Spoken English & Accent Reduction Masterclass",
    attendancePercent: 92,
    present: 42,
    absent: 2,
    late: 1,
    watchTime: "45h 20m",
    progressPercent: 78,
    riskLevel: "Low",
  },
  {
    id: "rep-002",
    name: "Sarah Chen",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704e",
    course: "Executive Business Communication",
    attendancePercent: 45,
    present: 12,
    absent: 10,
    late: 4,
    watchTime: "12h 15m",
    progressPercent: 22,
    riskLevel: "High",
  },
  {
    id: "rep-003",
    name: "Marcus Johnson",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704f",
    course: "Spoken English & Accent Reduction Masterclass",
    attendancePercent: 98,
    present: 45,
    absent: 0,
    late: 0,
    watchTime: "60h 00m",
    progressPercent: 95,
    riskLevel: "Low",
  },
  {
    id: "rep-004",
    name: "Elena Rodriguez",
    avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
    course: "Advanced English Grammar & Vocabulary",
    attendancePercent: 65,
    present: 20,
    absent: 8,
    late: 3,
    watchTime: "22h 45m",
    progressPercent: 45,
    riskLevel: "Medium",
  },
  {
    id: "rep-005",
    name: "Yuki Tanaka",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704c",
    course: "Executive Business Communication",
    attendancePercent: 88,
    present: 38,
    absent: 3,
    late: 2,
    watchTime: "35h 10m",
    progressPercent: 60,
    riskLevel: "Low",
  },
];

export const MOCK_TRENDS = [
  { date: "Mon", attendance: 85, watchTime: 120 },
  { date: "Tue", attendance: 92, watchTime: 140 },
  { date: "Wed", attendance: 88, watchTime: 135 },
  { date: "Thu", attendance: 95, watchTime: 160 },
  { date: "Fri", attendance: 78, watchTime: 90 },
  { date: "Sat", attendance: 45, watchTime: 200 },
  { date: "Sun", attendance: 60, watchTime: 250 },
];
