import { Student } from "@/stores/student.store";

export const MOCK_STUDENTS: Student[] = [
  {
    id: "stu-001",
    name: "Alex Rivera",
    email: "alex.rivera@example.com",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    country: "US",
    enrolledCourses: 2,
    attendance: 92,
    progress: 78,
    paymentStatus: "Paid",
    lastActive: "2 hours ago",
    joinedDate: "Mar 15, 2026",
    status: "Active",
    revenue: 450,
  },
  {
    id: "stu-002",
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704e",
    country: "CA",
    enrolledCourses: 1,
    attendance: 45,
    progress: 22,
    paymentStatus: "Pending",
    lastActive: "3 days ago",
    joinedDate: "Jul 01, 2026",
    status: "Inactive",
    revenue: 150,
  },
  {
    id: "stu-003",
    name: "Marcus Johnson",
    email: "marcus.j@example.com",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704f",
    country: "UK",
    enrolledCourses: 3,
    attendance: 100,
    progress: 95,
    paymentStatus: "Paid",
    lastActive: "Just now",
    joinedDate: "Jan 10, 2026",
    status: "Active",
    revenue: 890,
  },
  {
    id: "stu-004",
    name: "Elena Rodriguez",
    email: "elena.rodriguez@example.com",
    avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
    country: "ES",
    enrolledCourses: 1,
    attendance: 12,
    progress: 5,
    paymentStatus: "Overdue",
    lastActive: "1 month ago",
    joinedDate: "Feb 28, 2026",
    status: "Suspended",
    revenue: 0,
  },
  {
    id: "stu-005",
    name: "Yuki Tanaka",
    email: "yuki.t@example.com",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704c",
    country: "JP",
    enrolledCourses: 2,
    attendance: 88,
    progress: 60,
    paymentStatus: "Paid",
    lastActive: "Yesterday",
    joinedDate: "May 12, 2026",
    status: "Active",
    revenue: 600,
  },
];
