"""Cryptographic token generation utilities.

Provides generation and hashing primitives for tokens that are NOT
JWTs — specifically refresh tokens, password reset tokens, and email
verification tokens.

Security model:
    Raw tokens are generated with Python's ``secrets`` module (CSPRNG).
    Only the SHA-256 hash of each raw token is persisted in the database.
    If the database is breached, raw tokens cannot be recovered.

    Raw token format: 64 hex characters = 32 random bytes = 256-bit entropy.
    Hash format: 64 hex characters (SHA-256 of the raw token).

Usage pattern::

    raw_token = generate_raw_token()       # Send to user via email/cookie
    token_hash = hash_token(raw_token)     # Store in database

    # On verification:
    stored_token = db.get_by_hash(hash_token(raw_token_from_user))
"""

from __future__ import annotations

import hashlib
import secrets


def generate_raw_token(byte_length: int = 32, nbytes: int | None = None) -> str:
    """Generate a cryptographically secure random token.

    Uses Python's ``secrets.token_hex`` which reads from the OS CSPRNG
    (``/dev/urandom`` on Linux). The resulting string is 2 × ``byte_length``
    hex characters long.

    Args:
        byte_length: Number of random bytes to generate. Default 32
            produces 64 hex characters = 256 bits of entropy.
            Must be at least 16 (128-bit minimum for security).
        nbytes: Alias for byte_length for backward compatibility.

    Returns:
        str: Lowercase hex string of length ``2 * byte_length``.
            Example (32 bytes): ``"a3f8b2c1d4e5..."`` (64 chars)

    Raises:
        ValueError: If ``byte_length`` is less than 16.
    """
    length = nbytes if nbytes is not None else byte_length
    if length < 16:
        raise ValueError(
            f"byte_length must be at least 16 for security. Got {length}."
        )
    return secrets.token_hex(length)


def hash_token(raw_token: str) -> str:
    """Compute the SHA-256 hex digest of a raw token.

    This is the value stored in the database. The raw token itself is
    NEVER stored — only this hash. A successful login/reset/verify
    recomputes the hash from the submitted token and looks it up in the DB.

    Args:
        raw_token: The raw hex token string generated by ``generate_raw_token``.

    Returns:
        str: 64-character lowercase hex SHA-256 digest.
    """
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


def generate_otp(length: int = 6) -> str:
    """Generate a numeric one-time password (OTP).

    Each digit is generated independently from the OS CSPRNG via
    ``secrets.randbelow(10)`` to ensure uniform distribution.
    This avoids modulo bias that would occur with ``random.randint``.

    Args:
        length: Number of digits in the OTP. Default is 6.
            Common values: 4 (low security), 6 (standard), 8 (high security).

    Returns:
        str: Numeric string of the specified length.
            Example: ``"482931"``
    """
    return "".join(str(secrets.randbelow(10)) for _ in range(length))


def constant_time_compare(val1: str, val2: str) -> bool:
    """Compare two strings in constant time to prevent timing attacks.

    Uses ``hmac.compare_digest`` which is constant-time regardless of
    where the strings differ. This prevents timing oracle attacks where
    an attacker can infer how many characters match by measuring response
    times.

    Args:
        val1: First string.
        val2: Second string.

    Returns:
        bool: True if the strings are identical.
    """
    import hmac
    return hmac.compare_digest(
        val1.encode("utf-8"),
        val2.encode("utf-8"),
    )
