/**
 * TanStack Query key factory.
 *
 * All query keys are generated by this central factory. This
 * pattern guarantees:
 * - Consistent cache key structure across the app
 * - Type-safe query key arrays
 * - Precise, predictable cache invalidation
 *
 * Usage:
 *   useQuery({ queryKey: queryKeys.courses.detail(courseId), ... })
 *   queryClient.invalidateQueries({ queryKey: queryKeys.courses.all() })
 */

export const queryKeys = {
  // --- Auth ---
  auth: {
    me: () => ["auth", "me"] as const,
  },

  // --- Courses ---
  courses: {
    all: (filters?: Record<string, unknown>) =>
      filters ? ["courses", "list", filters] as const : ["courses", "list"] as const,
    detail: (id: string) => ["courses", "detail", id] as const,
    lectures: (courseId: string) => ["courses", courseId, "lectures"] as const,
    lecture: (courseId: string, lectureId: string) =>
      ["courses", courseId, "lectures", lectureId] as const,
    progress: (courseId: string) => ["courses", courseId, "progress"] as const,
    students: (courseId: string, filters?: Record<string, unknown>) =>
      filters
        ? ["courses", courseId, "students", filters] as const
        : ["courses", courseId, "students"] as const,
  },

  // --- Enrollments ---
  enrollments: {
    mine: () => ["enrollments", "mine"] as const,
    detail: (courseId: string) => ["enrollments", courseId] as const,
  },

  // --- Meetings ---
  meetings: {
    all: (courseId?: string) =>
      courseId ? ["meetings", "list", courseId] as const : ["meetings", "list"] as const,
    detail: (id: string) => ["meetings", id] as const,
    upcoming: () => ["meetings", "upcoming"] as const,
  },

  // --- Notifications ---
  notifications: {
    all: () => ["notifications", "list"] as const,
    unreadCount: () => ["notifications", "unread-count"] as const,
  },

  // --- Payments ---
  payments: {
    all: (filters?: Record<string, unknown>) =>
      filters ? ["payments", "list", filters] as const : ["payments", "list"] as const,
    detail: (id: string) => ["payments", id] as const,
  },

  // --- Chat ---
  chat: {
    messages: (roomId: string, cursor?: string) =>
      cursor
        ? ["chat", roomId, "messages", cursor] as const
        : ["chat", roomId, "messages"] as const,
  },

  // --- Analytics ---
  analytics: {
    teacher: (teacherId: string) => ["analytics", "teacher", teacherId] as const,
    course: (courseId: string) => ["analytics", "course", courseId] as const,
  },

  // --- Students (teacher view) ---
  students: {
    all: (filters?: Record<string, unknown>) =>
      filters ? ["students", "list", filters] as const : ["students", "list"] as const,
    detail: (id: string) => ["students", id] as const,
    attendance: (studentId: string) => ["students", studentId, "attendance"] as const,
  },
} as const;
